# Site settings
title: PrefixAutomata
email: 2221329554@qq.com
description: > 
  Never Give Up      
baseurl: "" 
url: "http://PrefixAutomataSong.github.io"
github_username:  PrefixAutomataSong

# Build settings
markdown: kramdown
