# Site settings
title: PrefixAutumata
email: your-email@domain.com
description: > 
  Never Give Up      
baseurl: "" 
url: "http://PrefixAutumataSong.github.io"
github_username:  PrefixAutumataSong

# Build settings
markdown: kramdown
